### ISSUE TITLE
Will this project be updated to API v2

### ISSUE THREAD

**Issue by weibel** [Smartling/api-sdk-ruby#10]
We're using this project for a collection of rake tasks we use for sending and receiving strings to Smarling. 
Will you update it to API v2?

**Comment by thil-rb** [comment]
We were looking for an update for V2 as well.. and we have since created a gem to support v2  https://github.com/redbubble/smartling_api

This is still a work in progress and still needs to support some end points so if you want to contribute most welcome :)

**Comment by foo4u** [comment]
@weibel @thil-rb we will be releasing API v2 support shortly.

**Comment by foo4u** [comment]
[v2.0.0 released][0] supporting API v2.

[0]: https://rubygems.org/gems/smartling
