### ISSUE TITLE
Issues with Api.rb

### ISSUE THREAD

**Issue by vvohra** [Smartling/api-sdk-ruby#14]
1. `@refreshToken` should be `@refresh` : https://github.com/Smartling/api-sdk-ruby/blob/master/lib/smartling/api.rb#L168

2. Tokens are being cached, but it's possible that a token could be like 1 second away from expiring when checked so it's valid, but when it is used the token has expired. I'm not sure there's a foolproof of dealing with this. 

I'm using a library that you pass it a list of pre-configured requests that are fetched in parallel with a limit. But it's possible (and has happened) that the token is expired by the time a request is made. I monkey-patched my code to confirm that a token is at least 60 seconds away from expiration.

**Comment by vvohra** [comment]
I can do 1, but would like some feedback on whether we should make a "force-refresh" for `token_header()`.

**Comment by foo4u** [comment]
Hi @vvohra we'll look into this. There's a reliable way to introspect the token to tell if it's about to expire.

**Comment by emilienh** [comment]
Fixed with https://github.com/Smartling/api-sdk-ruby/tree/v2.0.3. Thanks for your feedback.
