### ISSUE TITLE
Unsupported File Type

### ISSUE THREAD

**Issue by melissanoelle** [Smartling/api-sdk-ruby#6]
Here's my code:

```
smartling = Smartling::File.sandbox(:apiKey => api_key, :projectId => project_id)
text = "automation_test.txt"
file_uri = "automation/automation_test.txt"
file_type = "txt"

@result = smartling.upload(text, file_uri, file_type)
```

And it gives me this error:
> API error: VALIDATION_ERROR File type "txt" is not supported

However, the docs here: http://docs.smartling.com/pages/supported-file-types/Plain-Text/ say that the .txt file format is a supported file format. 

I thought that perhaps I had to enable this file format in my Smartling API panel or translation settings, but I couldn't find anything related to it. I also can't find anything in the docs about enabling certain file types. Help?

**Comment by jaredyv** [comment]
The Docs article has a typo, as the file_type should be "plainText" not "txt".  This will be corrected in the documentation in a few moments.  Thanks!

**Comment by melissanoelle** [comment]
Perfect, that worked. Thanks!
