### ISSUE TITLE
404 Resource Not Found

### ISSUE THREAD

**Issue by melissanoelle** [Smartling/api-sdk-ruby#9]
```
def request_translation
  api_key = Rails.application.secrets.smartling_api_key
  project_id = Rails.application.secrets.smartling_project_id

  smartling = Smartling::File.sandbox(:apiKey => api_key, :projectId => project_id)
  text = self.translation.file_name
  file_uri = self.translation.content_id.to_s
  file_type = "json"

  result = smartling.upload(text, file_uri, file_type)
end
```

Is giving me this:
> RuntimeError at /translation
> 404 Resource Not Found | text/html 464 bytes
and points to the error as being in `result = smartling.upload(text, file_uri, file_type)`.

When I test file.read(text) (from above), it outputs the file just fine.

Values:

text = `"/Users/madamaitis/repos/babel/translations/318719991.json"`
file_uri = `"318719991"`
file_type = `"json"`
result = `nil`

Any thoughts/ideas?

**Comment by paiv** [comment]
@melissanoelle you are using `sandbox` endpoint, which is no longer available

**Comment by melissanoelle** [comment]
Thanks, I forgot about that.
